# Generated by Django 5.2.8 on 2025-11-14 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_name', models.TextField()),
                ('track_id', models.TextField()),
                ('track_popularity', models.IntegerField()),
                ('artist_name', models.TextField()),
                ('artist_id', models.TextField()),
                ('release_year', models.DateField()),
                ('duration_ms', models.IntegerField()),
                ('track_image_link', models.URLField()),
            ],
        ),
    ]
